import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { FinancialService } from '../../../core/services/financial.service';
import { ApiService } from '../../../core/services/api';
import { CreateInvoiceRequest, UpdateInvoiceRequest, InvoiceLineItem, Invoice } from '../../../core/models/financial.model';
import { Customer } from '../../../core/models/customer.model';
import { Load } from '../../../core/models/load.model';

@Component({
  selector: 'app-invoice-create',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './invoice-create.html',
  styleUrl: './invoice-create.scss',
})
export class InvoiceCreateComponent implements OnInit {
  isEditMode = false;
  invoiceId?: number;
  loading = false;
  submitting = false;
  
  customers: Customer[] = [];
  loads: Load[] = [];
  
  formData: any = {
    invoiceNumber: '', // Will be auto-generated by backend
    customerId: 0,
    issueDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    subTotal: 0,
    taxAmount: 0,
    totalAmount: 0,
    currency: 'USD',
    notes: '',
    terms: '',
    status: '',
    lineItems: []
  };

  taxRate = 0.08; // 8% default tax rate

  constructor(
    private financialService: FinancialService,
    private apiService: ApiService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.isEditMode = true;
        this.invoiceId = +params['id'];
        this.loadInvoice();
      }
    });
    this.loadCustomers();
    this.loadLoads();
  }

  loadCustomers(): void {
    this.apiService.get<Customer[]>('customers').subscribe({
      next: (data) => {
        this.customers = data;
      }
    });
  }

  loadLoads(): void {
    this.apiService.get<Load[]>('loads').subscribe({
      next: (data) => {
        this.loads = data.filter(l => l.status === 'Delivered');
      }
    });
  }

  loadInvoice(): void {
    if (!this.invoiceId) return;
    this.loading = true;
    this.financialService.getInvoiceById(this.invoiceId).subscribe({
      next: (invoice) => {
        this.formData = {
          invoiceId: invoice.invoiceId,
          invoiceNumber: invoice.invoiceNumber,
          customerId: invoice.customerId,
          loadId: invoice.loadId,
          issueDate: invoice.issueDate.split('T')[0],
          dueDate: invoice.dueDate?.split('T')[0],
          subTotal: invoice.subTotal,
          taxAmount: invoice.taxAmount,
          totalAmount: invoice.totalAmount,
          currency: invoice.currency || 'USD',
          notes: (invoice as any).notes || '',
          terms: (invoice as any).terms || '',
          status: invoice.status,
          lineItems: invoice.lineItems.map(li => ({
            lineItemId: li.lineItemId,
            description: li.description,
            quantity: li.quantity,
            unitPrice: li.unitPrice,
            amount: li.amount,
            itemType: li.itemType || 'Other',
            loadId: li.loadId,
            accessorialId: li.accessorialId
          }))
        };
        // Calculate tax rate from existing invoice
        if (invoice.subTotal > 0) {
          this.taxRate = invoice.taxAmount / invoice.subTotal;
        }
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  addLineItem(): void {
    this.formData.lineItems.push({
      description: '',
      quantity: 1,
      unitPrice: 0,
      amount: 0,
      itemType: 'Other'
    });
    this.calculateTotals();
  }

  removeLineItem(index: number): void {
    this.formData.lineItems.splice(index, 1);
    this.calculateTotals();
  }

  updateLineItem(index: number): void {
    const item = this.formData.lineItems[index];
    item.amount = item.quantity * item.unitPrice;
    this.calculateTotals();
  }

  calculateTotals(): void {
    this.formData.subTotal = this.formData.lineItems.reduce((sum: number, item: any) => sum + (item.amount || 0), 0);
    this.formData.taxAmount = this.formData.subTotal * this.taxRate;
    this.formData.totalAmount = this.formData.subTotal + this.formData.taxAmount;
  }

  onSubmit(): void {
    if (this.isEditMode && this.invoiceId) {
      this.updateInvoice();
    } else {
      this.createInvoice();
    }
  }

  createInvoice(): void {
    this.submitting = true;
    // Don't send invoiceNumber when creating - backend will auto-generate it
    const { invoiceNumber, ...createRequest } = this.formData;
    this.financialService.createInvoice(createRequest as CreateInvoiceRequest).subscribe({
      next: () => {
        this.router.navigate(['/financial/invoices']);
      },
      error: () => {
        this.submitting = false;
      }
    });
  }

  updateInvoice(): void {
    if (!this.invoiceId) return;
    this.submitting = true;
    const updateRequest: UpdateInvoiceRequest = {
      invoiceId: this.invoiceId,
      invoiceNumber: this.formData.invoiceNumber,
      customerId: this.formData.customerId,
      issueDate: this.formData.issueDate,
      dueDate: this.formData.dueDate,
      subTotal: this.formData.subTotal,
      taxAmount: this.formData.taxAmount,
      totalAmount: this.formData.totalAmount,
      notes: this.formData.notes,
      terms: this.formData.terms,
      status: this.formData.status,
      lineItems: this.formData.lineItems
    };
    this.financialService.updateInvoice(this.invoiceId, updateRequest).subscribe({
      next: () => {
        this.router.navigate(['/financial/invoices']);
      },
      error: () => {
        this.submitting = false;
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/financial/invoices']);
  }

  formatCurrency(amount: number): string {
    const currency = this.formData.currency || 'USD';
    return new Intl.NumberFormat('en-US', { 
      style: 'currency', 
      currency: currency 
    }).format(amount || 0);
  }

  getCurrencySymbol(): string {
    const currencyMap: { [key: string]: string } = {
      'USD': '$',
      'CAD': 'C$',
      'EUR': '€'
    };
    return currencyMap[this.formData.currency || 'USD'] || '$';
  }

  getStatusIcon(status: string): string {
    const iconMap: { [key: string]: string } = {
      'Draft': 'fa-edit',
      'Sent': 'fa-paper-plane',
      'Paid': 'fa-check-circle',
      'Overdue': 'fa-exclamation-triangle',
      'Cancelled': 'fa-times-circle'
    };
    return iconMap[status] || 'fa-file-invoice';
  }

  getStatusClass(status: string): string {
    return `status-${status.toLowerCase()}`;
  }
}

